services:
  reth0:
    image: ghcr.io/metisprotocol/hyperion:v0.3.0
    container_name: reth0
    volumes:
      - ./rethdata:/data/reth/execution-data
      - .configs/assets:/root/assets/
    ports:
      - "8545:8545"
      - "8551:8551"
      - "9100:9001"
      - "30303:30303"
      - "30303:30303/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command:
      - "node"
      - "-vvvvv"
      - "-d"
      - "--datadir=/data/reth/execution-data"
      - "--chain=/root/assets/genesis.json"
      - "--http"
      - "--http.port=8545"
      - "--http.addr=0.0.0.0"
      - "--http.corsdomain=*"
      - "--http.api=admin,net,eth,web3,debug,txpool,trace"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.port=8551"
      - "--authrpc.jwtsecret=/root/assets/jwtsecret"
      - "--metrics=0.0.0.0:9001"
      - "--discovery.port=30303"
      - "--port=30303"
      # - "--builder.gaslimit=3600000000" # default * 100
      # - "--builder.interval=10ms"
      # - "--builder.deadline=1" # The deadline in seconds for when the payload builder job should resolve
      # - "--builder.max-tasks=10" # default=3
      # - "--txpool.gas-limit=300000000" # default * 10
      # - "--blobpool.pricebump=1"
      # - "--txpool.pending-max-count=50000" # default=10000
      # - "--txpool.queued-max-count=50000" # default=10000
  mala0:
    image: chengzhinei2/malaketh-layered:v1.0.0
    container_name: mala0
    volumes:
      - ./configs/node/:/data
      - ./configs/assets:/app/assets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PATH: /app
    command:
      # - "malachitebft-eth-app"
      - "start"
      #- "--start-height=267"
      - "--home"
      - "/data"
  grafana:
    image: grafana/grafana-oss
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '501'
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./monitoring/data-grafana:/var/lib/grafana
      - ./monitoring/config-grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/config-grafana/grafana.ini:/etc/grafana/grafana.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GF_LOG_LEVEL: info
      GF_ANALYTICS_ENABLED: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_ANALYTICS_FEEDBACK_LINKS_ENABLED: false
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards-data/default.json
      GF_USERS_DEFAULT_THEME: system
      GF_USERS_EDITORS_CAN_ADMIN: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
      GF_AUTH_BASIC_ENABLED: false
      GF_NEWS_NEWS_FEED_ENABLED: false
