apiVersion: v1
kind: ConfigMap
metadata:
  name: node3-configs
  namespace: lazai
data:
  config.toml: |
    moniker = "validator-2"

    [engine]
    engine_url = "http://localhost:8551"
    eth_url = "http://localhost:8545"
    wt_path = "/data/jwt.hex"
    block_interval = "1s"

    [logging]
    log_level = "debug"
    log_format = "plaintext"

    [consensus]
    timeout_propose = "3s"
    timeout_propose_delta = "500ms"
    timeout_prevote = "1s"
    timeout_prevote_delta = "500ms"
    timeout_precommit = "1s"
    timeout_precommit_delta = "500ms"
    timeout_rebroadcast = "5s"
    value_payload = "proposal-and-parts"
    queue_capacity = 100

    [consensus.p2p]
    #listen_addr = "/ip4/0.0.0.0/tcp/27002"
    listen_addr = "/ip4/0.0.0.0/tcp/27000"
    persistent_peers = [
      #"/ip4/127.0.0.1/tcp/27000",
      #"/ip4/127.0.0.1/tcp/27001",
      "/dns/seq1/tcp/27000",
      "/dns/seq2/tcp/27000",
    ]
    pubsub_max_size = "4.2 MB"
    rpc_max_size = "10.5 MB"

    [consensus.p2p.discovery]
    enabled = true
    bootstrap_protocol = "full"
    selector = "random"
    num_outbound_peers = 20
    num_inbound_peers = 20
    max_connections_per_peer = 5
    ephemeral_connection_timeout = "5s"

    [consensus.p2p.protocol]
    type = "gossipsub"
    mesh_n = 6
    mesh_n_high = 12
    mesh_n_low = 4
    mesh_outbound_min = 2

    [value_sync]
    enabled = true
    status_update_interval = "10s"
    request_timeout = "10s"
    max_request_size = "1048.6 KB"
    max_response_size = "536.9 MB"
    parallel_requests = 5
    scoring_strategy = "ema"
    inactive_threshold = "1m"

    [metrics]
    enabled = true
    listen_addr = "127.0.0.1:29000"

    [runtime]
    flavor = "single_threaded"

    [prune]
    enabled = true
    retain_heights = 5000
  genesis.json: |
    {
      "validator_set": {
        "validators": [
          {
            "address": "0x3def90af7dee89f94661b6b2d16ebd0b8cd4ce7a",
            "public_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "4I4Dbek9FCwFrfacA7PAFyC5s4k+D/CDjMyibLTRGcY="
            },
            "voting_power": 1
          },
          {
            "address": "0x9aa584959ca3a1a26b70871b2abf4cbb8f8321ba",
            "public_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "PVhttyWSswTN5dawA03ogVPt/oaGPno6qq7jhhGqHWM="
            },
            "voting_power": 1
          },
          {
            "address": "0xc52b8bdbbc8a318324fd10a3c4e0d3dc00a376ee",
            "public_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "zTCaj4cFmxz5tpZHgS83ILhhmNGdXW0FKeu3f0pOV7c="
            },
            "voting_power": 1
          }
        ]
      }
    }
  priv_validator_key.json: |
    {
      "type": "tendermint/PrivKeyEd25519",
      "value": "/UZSWG/OJ7/sgg0vQ5+MR6REWqUQvY6wxN3Mun1AKoY="
    }
