apiVersion: v1
kind: Service
metadata:
  name: seq3
  labels:
    app: seq3
spec:
  ports:
    - protocol: TCP
      targetPort: 8545
      port: 8545
      name: jsonrpc
    - protocol: TCP
      targetPort: 8546
      port: 8546
      name: websocket
    - protocol: TCP
      targetPort: 9001
      port: 9001
      name: metrics
    - protocol: TCP
      targetPort: 27000
      port: 27000
      name: p2p
  selector:
    app: seq3
