moniker = "app-3"

[engine]
engine_url = "http://localhost:38551"
eth_url = "http://localhost:38545"
wt_path = "./assets/jwtsecret"
block_interval = "1s"

[logging]
log_level = "debug"
log_format = "plaintext"

[consensus]
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_rebroadcast = "5s"
value_payload = "proposal-and-parts"
queue_capacity = 100

[consensus.p2p]
listen_addr = "/ip4/0.0.0.0/tcp/27003"
persistent_peers = [
    "/ip4/127.0.0.1/tcp/27000",
    "/ip4/127.0.0.1/tcp/27001",
    "/ip4/127.0.0.1/tcp/27002",
]
pubsub_max_size = "4.2 MB"
rpc_max_size = "10.5 MB"

[consensus.p2p.discovery]
enabled = false
bootstrap_protocol = "full"
selector = "random"
num_outbound_peers = 20
num_inbound_peers = 20
max_connections_per_peer = 5
ephemeral_connection_timeout = "5s"

[consensus.p2p.protocol]
type = "gossipsub"
mesh_n = 6
mesh_n_high = 12
mesh_n_low = 4
mesh_outbound_min = 2

[value_sync]
enabled = true
status_update_interval = "10s"
request_timeout = "10s"
max_request_size = "1048.6 KB"
max_response_size = "536.9 MB"
parallel_requests = 5
scoring_strategy = "ema"
inactive_threshold = "1m"

[metrics]
enabled = true
listen_addr = "127.0.0.1:29003"

[runtime]
flavor = "single_threaded"

[prune]
enabled = true
retain_heights = 5000
