[package]
name = "metis-app-options"
version = "0.1.0"
edition = "2024"

[dependencies]
metis-primitives.workspace = true

clap.workspace = true
tracing.workspace = true
tendermint-rpc.workspace = true
