[package]
name = "metis-hook"
version.workspace = true
edition.workspace = true

[dependencies]
revm.workspace = true
metis-primitives.workspace = true
alloy-evm.workspace = true
alloy-primitives.workspace = true
reth-evm.workspace = true