apiVersion: v1
kind: ConfigMap
metadata:
  name: node1-configs
  namespace: lazai
data:
  app_config.toml: |
    engine_url = "http://127.0.0.1:8551"
    eth_url = "http://127.0.0.1:8545"
    wt_path = "/data/jwt.hex"
  config.toml: |
    moniker = "validator-0"

    [logging]
    log_level = "debug"
    log_format = "plaintext"

    [consensus]
    timeout_propose = "3s"
    timeout_propose_delta = "500ms"
    timeout_prevote = "1s"
    timeout_prevote_delta = "500ms"
    timeout_precommit = "1s"
    timeout_precommit_delta = "500ms"
    timeout_commit = "0s"
    timeout_step = "30s"

    [consensus.p2p]
    listen_addr = "/ip4/0.0.0.0/tcp/27000"
    persistent_peers = [
        "/ip4/127.0.0.1/tcp/27001",
        "/ip4/127.0.0.1/tcp/27002",
    ]
    transport = "tcp"
    pubsub_max_size = "4.2 MB"
    rpc_max_size = "10.5 MB"

    [consensus.p2p.discovery]
    enabled = true
    bootstrap_protocol = "full"
    selector = "random"
    num_outbound_peers = 20
    num_inbound_peers = 20
    ephemeral_connection_timeout = "5s"

    [consensus.p2p.protocol]
    type = "gossipsub"
    mesh_n = 6
    mesh_n_high = 12
    mesh_n_low = 4
    mesh_outbound_min = 2

    [mempool]
    max_tx_count = 10000
    gossip_batch_size = 0

    [mempool.p2p]


    listen_addr = "/ip4/127.0.0.1/tcp/28000"
    persistent_peers = [
        "/ip4/127.0.0.1/tcp/28001",
        "/ip4/127.0.0.1/tcp/28002",
    ]
    transport = "tcp"
    pubsub_max_size = "4.2 MB"
    rpc_max_size = "10.5 MB"

    [mempool.p2p.discovery]
    enabled = false
    bootstrap_protocol = "full"
    selector = "random"
    num_outbound_peers = 20
    num_inbound_peers = 20
    ephemeral_connection_timeout = "5s"

    [mempool.p2p.protocol]
    type = "gossipsub"
    mesh_n = 6
    mesh_n_high = 12
    mesh_n_low = 4
    mesh_outbound_min = 2

    [sync]
    enabled = true
    status_update_interval = "10s"
    request_timeout = "10s"

    [metrics]
    enabled = true
    listen_addr = "127.0.0.1:29000"

    [runtime]
    flavor = "single_threaded"

    [test]
    max_block_size = "1048.6 KB"
    value_payload = "parts-only"
    tx_size = "1.0 KB"
    txs_per_part = 256
    time_allowance_factor = 0.5
    exec_time_per_tx = "1ms"
    max_retain_blocks = 1000

    [test.vote_extensions]
    enabled = false
    size = "0 B"
  genesis.json: |
    {
      "validator_set": {
        "validators": [
          {
            "address": "0x3def90af7dee89f94661b6b2d16ebd0b8cd4ce7a",
            "public_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "4I4Dbek9FCwFrfacA7PAFyC5s4k+D/CDjMyibLTRGcY="
            },
            "voting_power": 1
          },
          {
            "address": "0x9aa584959ca3a1a26b70871b2abf4cbb8f8321ba",
            "public_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "PVhttyWSswTN5dawA03ogVPt/oaGPno6qq7jhhGqHWM="
            },
            "voting_power": 1
          },
          {
            "address": "0xc52b8bdbbc8a318324fd10a3c4e0d3dc00a376ee",
            "public_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "zTCaj4cFmxz5tpZHgS83ILhhmNGdXW0FKeu3f0pOV7c="
            },
            "voting_power": 1
          }
        ]
      }
    }
  priv_validator_key.json: |
    {
      "type": "tendermint/PrivKeyEd25519",
      "value": "lxupTIP9eOdVszL7uONRqET6vUc+G6fJhrYdQAcsSRY="
    }
  jwt.hex: |
    167814d140ef5b51febc9b2aa29c08dba3b67e0a343352722d33d1570e9fbfa1