name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
    types: [synchronize, opened, reopened, converted_to_draft, ready_for_review]

env:
  LLVM_MAJOR_VERSION: "18"
  RUST_VERSION: 1.85
  MACOSX_DEPLOYMENT_TARGET: '12.0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bench:
    name: Benchmark Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy, rustfmt

      - name: Checkout base
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref || 'main' }}
          fetch-depth: 2
      - name: Checkout HEAD^
        if: ${{ !github.base_ref }}
        run: git checkout HEAD^
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Save benchmark baseline
        run: JEMALLOC_SYS_WITH_MALLOC_CONF="thp:always,metadata_thp:always" cargo bench -p metis-pe --features jemalloc
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Compare PR benchmarks
        run: JEMALLOC_SYS_WITH_MALLOC_CONF="thp:always,metadata_thp:always" cargo bench -p metis-pe --features jemalloc
