name: Ethertest

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
    types: [synchronize, opened, reopened, converted_to_draft, ready_for_review]

env:
  LLVM_MAJOR_VERSION: "18"
  RUST_VERSION: 1.88
  MACOSX_DEPLOYMENT_TARGET: '12.0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Ethertest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run ethertest state suites
        run: |
          cd crates/tools
          # Download ethereum state test suites
          git clone -b v17.1 https://github.com/ethereum/tests
          TEST_DIR=tests/GeneralStateTests
          cargo run -r --bin metis-ethertest run $TEST_DIR

          # Download EELS fixtures released at Cancun
          curl -LO https://github.com/ethereum/execution-spec-tests/releases/download/v2.1.1/fixtures.tar.gz && tar -xzf fixtures.tar.gz
          TEST_DIR=fixtures/state_tests
          cargo run -r --bin metis-ethertest run $TEST_DIR
