name: Kubernetes Deploy Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
    types: [synchronize, opened, reopened, converted_to_draft, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.14.0
        with:
          minikube version: 'v1.35.0'
          kubernetes version: 'v1.33.0'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Minikube setup
        run: |
          minikube status
          kubectl get nodes
          kubectl version

      - name: Setup Kustomize
        uses: fluxcd/pkg/actions/kustomize@main

      - name: Create necessary directories
        run: |
          cd devops
          mkdir -p configs/node  # Ensure mount directory exists
          echo "test config" > configs/node/test.conf

      - name: Run deployment tests
        run: |
          cd devops
          
          # Start background mount processes
          echo "Starting directory mounts..."
          minikube mount ./configs/node:/data/node1 &
          echo "Mount 1 PID: $!"
          minikube mount ./configs/node:/data/node2 &
          echo "Mount 2 PID: $!"
          minikube mount ./configs/node:/data/node3 &
          echo "Mount 3 PID: $!"
          
          # Wait for mounts to complete
          sleep 10
          
          # Create namespace
          kubectl create namespace hyperion --dry-run=client -o yaml | kubectl apply -f -
          
          # Deploy Kustomize configuration
          echo "Applying Kustomize manifests..."
          kustomize build k8s | kubectl apply -f -
          
          # Wait for deployment initialization
          echo "Waiting for deployment to stabilize..."
          sleep 15
          
          # Check resource status
          echo "Current cluster state:"
          kubectl get all -n hyperion
          kubectl get namespaces
          
          # Wait for StatefulSet to be ready
          echo "Waiting for StatefulSet pods to be ready..."
          if ! kubectl wait --for=condition=ready pod -l app=seq1 -n hyperion --timeout=300s; then
            echo "Pods failed to become ready within timeout"
            kubectl describe pods -l app=seq1 -n hyperion
            exit 1
          fi
          
          # Verify StatefulSet
          echo "Verifying StatefulSet..."
          if ! kubectl get statefulset seq1 -n hyperion &> /dev/null; then
            echo "StatefulSet seq1 not found"
            exit 1
          fi
          
          # Check replica status
          DESIRED_REPLICAS=$(kubectl get statefulset seq1 -n hyperion -o jsonpath='{.spec.replicas}')
          READY_REPLICAS=$(kubectl get statefulset seq1 -n hyperion -o jsonpath='{.status.readyReplicas}')
          
          echo "Desired replicas: $DESIRED_REPLICAS"
          echo "Ready replicas: $READY_REPLICAS"
          
          if [ "$READY_REPLICAS" -ne "$DESIRED_REPLICAS" ]; then
            echo "Not all replicas are ready"
            kubectl describe statefulset seq1 -n hyperion
            exit 1
          fi
          
          # View container logs
          echo "Retrieving mala container logs..."
          kubectl logs seq1-0 -c mala -n hyperion -f --tail=100

      - name: Cleanup
        if: always()
        run: |
          # Clean up Kubernetes resources
          cd devops
          kustomize build k8s | kubectl delete -f - --ignore-not-found=true
          
          # Stop Minikube
          minikube stop
          minikube delete
