name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

env:
  LLVM_MAJOR_VERSION: "18"
  RUST_VERSION: 1.86
  MACOSX_DEPLOYMENT_TARGET: '12.0'

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy, rustfmt

      - name: Add LLVM deb repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${{ env.LLVM_MAJOR_VERSION }} main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install LLVM
        run: |
          v=${{ env.LLVM_MAJOR_VERSION }}
          sudo apt-get install llvm-${v} llvm-${v}-dev llvm-${v}-runtime clang-${v} clang-tools-${v} lld-${v} libpolly-${v}-dev
          echo "LLVM_SYS_${v}0_PREFIX=/usr/lib/llvm-${v}/" >> $GITHUB_ENV
          echo "PATH=/usr/lib/llvm-${v}/bin:$PATH" >> $GITHUB_ENV

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo fmt
        run: make fmt-check
      - name: Cargo clippy
        run: make clippy
